package com.puccode.snacksclient.forms;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import stubs.APIResponse;
import stubs.Order;
import stubs.OrderID;
import stubs.clientGrpc;

public class Home extends javax.swing.JFrame {
    
    static ManagedChannel channel;
    clientGrpc.clientBlockingStub userStub;
    private int qtdCarrinho = 0;
    private final Carrinho carrinho;
    private int posicao = 1;
    
    public Home() {
        channel = ManagedChannelBuilder.forAddress("localhost",9090)
                    .usePlaintext()
                    .build();
        
        userStub = clientGrpc.newBlockingStub(channel);
        carrinho = new Carrinho();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        pane_cardone = new javax.swing.JPanel();
        name_order_one = new javax.swing.JLabel();
        img_order_one = new javax.swing.JLabel();
        descrip_order_one = new javax.swing.JLabel();
        input_qtd_one = new javax.swing.JTextField();
        qtd_order_one = new javax.swing.JLabel();
        btn_hamb = new javax.swing.JButton();
        pane_cardtwo = new javax.swing.JPanel();
        name_order_two = new javax.swing.JLabel();
        img_order_two = new javax.swing.JLabel();
        descrip_order_two = new javax.swing.JLabel();
        qtd_order_two = new javax.swing.JLabel();
        input_qtd_two = new javax.swing.JTextField();
        btn_pizza = new javax.swing.JButton();
        pane_cardthree = new javax.swing.JPanel();
        name_order_three = new javax.swing.JLabel();
        img_order_three = new javax.swing.JLabel();
        descrip_order_three = new javax.swing.JLabel();
        qtd_order_three = new javax.swing.JLabel();
        input_qtd_three = new javax.swing.JTextField();
        btn_past = new javax.swing.JButton();
        pane_head = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        panel_Cart = new javax.swing.JPanel();
        cart_title = new javax.swing.JLabel();
        cart_image = new javax.swing.JLabel();
        cart_circle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        jButton3.setText("Comprar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        pane_cardone.setBackground(new java.awt.Color(153, 189, 169));
        pane_cardone.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        name_order_one.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        name_order_one.setText("Hambúrguer");

        img_order_one.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/hamburguer (1).png"))); // NOI18N

        descrip_order_one.setBackground(new java.awt.Color(204, 204, 204));
        descrip_order_one.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        descrip_order_one.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descrip_order_one.setText("<html>Hambúrguer completo, 2 carnes, alface,<br/>tomate, picles e molho especial.</html>");
        descrip_order_one.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        descrip_order_one.setOpaque(true);

        input_qtd_one.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_qtd_one.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        qtd_order_one.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qtd_order_one.setText("Qtd:");

        btn_hamb.setBackground(new java.awt.Color(0, 102, 102));
        btn_hamb.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btn_hamb.setForeground(new java.awt.Color(255, 255, 255));
        btn_hamb.setText("Fazer pedido");
        btn_hamb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hambActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pane_cardoneLayout = new javax.swing.GroupLayout(pane_cardone);
        pane_cardone.setLayout(pane_cardoneLayout);
        pane_cardoneLayout.setHorizontalGroup(
            pane_cardoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descrip_order_one, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addGroup(pane_cardoneLayout.createSequentialGroup()
                .addGroup(pane_cardoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_cardoneLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pane_cardoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name_order_one)
                            .addComponent(img_order_one, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pane_cardoneLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(qtd_order_one, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pane_cardoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_hamb)
                            .addComponent(input_qtd_one, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pane_cardoneLayout.setVerticalGroup(
            pane_cardoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_cardoneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(name_order_one)
                .addGap(38, 38, 38)
                .addComponent(img_order_one)
                .addGap(27, 27, 27)
                .addComponent(descrip_order_one, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pane_cardoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qtd_order_one)
                    .addComponent(input_qtd_one, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btn_hamb)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pane_cardtwo.setBackground(new java.awt.Color(153, 189, 169));

        name_order_two.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        name_order_two.setText("Pizza");

        img_order_two.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pizza.png"))); // NOI18N

        descrip_order_two.setBackground(new java.awt.Color(204, 204, 204));
        descrip_order_two.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        descrip_order_two.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descrip_order_two.setText("<html>Pizza de calabresa: molho de tomate,<br/>calabresa, cebola, e tempero da casa.</html>");
        descrip_order_two.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        descrip_order_two.setOpaque(true);

        qtd_order_two.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qtd_order_two.setText("Qtd:");

        input_qtd_two.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_qtd_two.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btn_pizza.setBackground(new java.awt.Color(0, 102, 102));
        btn_pizza.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btn_pizza.setForeground(new java.awt.Color(255, 255, 255));
        btn_pizza.setText("Fazer pedido");
        btn_pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pizzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pane_cardtwoLayout = new javax.swing.GroupLayout(pane_cardtwo);
        pane_cardtwo.setLayout(pane_cardtwoLayout);
        pane_cardtwoLayout.setHorizontalGroup(
            pane_cardtwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descrip_order_two, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addGroup(pane_cardtwoLayout.createSequentialGroup()
                .addGroup(pane_cardtwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_cardtwoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(qtd_order_two, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_qtd_two, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pane_cardtwoLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btn_pizza)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pane_cardtwoLayout.createSequentialGroup()
                .addGroup(pane_cardtwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_cardtwoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(img_order_two))
                    .addGroup(pane_cardtwoLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(name_order_two)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pane_cardtwoLayout.setVerticalGroup(
            pane_cardtwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_cardtwoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(name_order_two)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(img_order_two, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(descrip_order_two, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pane_cardtwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_qtd_two, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtd_order_two))
                .addGap(39, 39, 39)
                .addComponent(btn_pizza)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane_cardthree.setBackground(new java.awt.Color(153, 189, 169));

        name_order_three.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        name_order_three.setText("Pastel");

        img_order_three.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pastel.jpg"))); // NOI18N

        descrip_order_three.setBackground(new java.awt.Color(204, 204, 204));
        descrip_order_three.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        descrip_order_three.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descrip_order_three.setText("<html>Pastel de frango com catupiry, <br/>bem recheado e saboroso!</html>");
        descrip_order_three.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        descrip_order_three.setOpaque(true);

        qtd_order_three.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qtd_order_three.setText("Qtd:");

        btn_past.setBackground(new java.awt.Color(0, 102, 102));
        btn_past.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btn_past.setForeground(new java.awt.Color(255, 255, 255));
        btn_past.setText("Fazer pedido");
        btn_past.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pane_cardthreeLayout = new javax.swing.GroupLayout(pane_cardthree);
        pane_cardthree.setLayout(pane_cardthreeLayout);
        pane_cardthreeLayout.setHorizontalGroup(
            pane_cardthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descrip_order_three)
            .addGroup(pane_cardthreeLayout.createSequentialGroup()
                .addGroup(pane_cardthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_cardthreeLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(img_order_three, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pane_cardthreeLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(qtd_order_three, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_qtd_three, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_cardthreeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pane_cardthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_cardthreeLayout.createSequentialGroup()
                        .addComponent(name_order_three)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_cardthreeLayout.createSequentialGroup()
                        .addComponent(btn_past)
                        .addGap(55, 55, 55))))
        );
        pane_cardthreeLayout.setVerticalGroup(
            pane_cardthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_cardthreeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(name_order_three)
                .addGap(18, 18, 18)
                .addComponent(img_order_three, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(descrip_order_three, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pane_cardthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtd_order_three)
                    .addComponent(input_qtd_three, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btn_past)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane_head.setBackground(new java.awt.Color(255, 0, 0));

        title.setBackground(Color.red);
        title.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Restaurante Java Snacks");

        javax.swing.GroupLayout pane_headLayout = new javax.swing.GroupLayout(pane_head);
        pane_head.setLayout(pane_headLayout);
        pane_headLayout.setHorizontalGroup(
            pane_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pane_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pane_headLayout.createSequentialGroup()
                    .addGap(431, 431, 431)
                    .addComponent(title)
                    .addContainerGap(432, Short.MAX_VALUE)))
        );
        pane_headLayout.setVerticalGroup(
            pane_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pane_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pane_headLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(title)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel_Cart.setBackground(new java.awt.Color(102, 102, 102));

        cart_title.setBackground(new java.awt.Color(255, 255, 255));
        cart_title.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cart_title.setForeground(new java.awt.Color(255, 255, 255));
        cart_title.setText("Carrinho");

        cart_image.setBackground(new java.awt.Color(255, 255, 255));
        cart_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/carrinho__1_-removebg-preview (2).png"))); // NOI18N

        cart_circle.setBackground(new java.awt.Color(102, 102, 102));
        cart_circle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cart_circle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/circle-removebg-preview (1).png"))); // NOI18N
        cart_circle.setText(Integer.toString(this.qtdCarrinho));
        cart_circle.setFocusable(false);
        cart_circle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cart_circle.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ver Carrinho");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_CartLayout = new javax.swing.GroupLayout(panel_Cart);
        panel_Cart.setLayout(panel_CartLayout);
        panel_CartLayout.setHorizontalGroup(
            panel_CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CartLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cart_image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cart_title)
                .addGap(18, 18, 18)
                .addComponent(cart_circle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
        );
        panel_CartLayout.setVerticalGroup(
            panel_CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_CartLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panel_CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_CartLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cart_title, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cart_image)
                    .addGroup(panel_CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cart_circle)
                        .addComponent(jButton1)))
                .addGap(14, 14, 14))
        );

        btn_cancel.setBackground(new java.awt.Color(255, 102, 102));
        btn_cancel.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btn_cancel.setText("Cancelar Pedido");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane_head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(pane_cardone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(pane_cardtwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(pane_cardthree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pane_head, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btn_cancel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pane_cardone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pane_cardtwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pane_cardthree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(panel_Cart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hambActionPerformed
        String nomePedido = this.name_order_one.getText();
        String quantidade = this.input_qtd_one.getText();
        String observacoes = "";
        int table;
        if (quantidade.equalsIgnoreCase("") || quantidade.equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(pane_cardone, "A quantidade não pode ser nula!");
        } else {
            table = Integer.parseInt(JOptionPane.showInputDialog(pane_cardone, "Qual número da mesa?"));
            int option = JOptionPane.showConfirmDialog(pane_cardone, "Possui alguma observação no pedido?");
            if (option == JOptionPane.YES_OPTION) {
                 observacoes = JOptionPane.showInputDialog(pane_cardone, "Digite as observações abaixo!");
            } else if (option == JOptionPane.CANCEL_OPTION) {
                JOptionPane.showMessageDialog(pane_cardone, "Cancelando pedido...");
                return;
            }
            
            Order myOrder = Order.newBuilder()
                    .setName(nomePedido)
                    .setCustomerTable(table)
                    .setObservations(observacoes)
                    .setQuantidade(Long.parseLong(quantidade))
                    .build();
            
            APIResponse response = userStub.registerOrder(myOrder);
            JOptionPane.showMessageDialog(pane_cardone, response.getResponseMessage());
            
            if (response.getMessageCode() == 200) {
                try {
                    this.qtdCarrinho++;
                    this.cart_circle.setText(Integer.toString(this.qtdCarrinho));
                    this.carrinho.addOrderToCart(myOrder);
                    JOptionPane.showMessageDialog(pane_cardone, "Seu pedido é o número " + posicao +" :D");
                    posicao++;
                } catch (Exception ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btn_hambActionPerformed

    private void btn_pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pizzaActionPerformed
        String nomePedido = this.name_order_two.getText();
        String quantidade = this.input_qtd_two.getText();
        String observacoes = "";
        int table;
        if (quantidade.equalsIgnoreCase("") || quantidade.equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(pane_cardtwo, "A quantidade não pode ser nula!");
        } else {
            table = Integer.parseInt(JOptionPane.showInputDialog(pane_cardtwo, "Qual número da mesa?"));
            int option = JOptionPane.showConfirmDialog(pane_cardtwo, "Possui alguma observação no pedido?");
            if (option == JOptionPane.YES_OPTION) {
                 observacoes = JOptionPane.showInputDialog(pane_cardtwo, "Digite as observações abaixo!");
            } else if (option == JOptionPane.CANCEL_OPTION) {
                JOptionPane.showMessageDialog(pane_cardtwo, "Cancelando pedido...");
                return;
            }

            Order myOrder = Order.newBuilder()
                    .setName(nomePedido)
                    .setCustomerTable(table)
                    .setObservations(observacoes)
                    .setQuantidade(Long.parseLong(quantidade))
                    .build();
            
            APIResponse response = userStub.registerOrder(myOrder);
            JOptionPane.showMessageDialog(pane_cardtwo, response.getResponseMessage());
            
            if (response.getMessageCode() == 200) {
                try {
                    this.qtdCarrinho++;
                    this.cart_circle.setText(Integer.toString(this.qtdCarrinho));
                    this.carrinho.addOrderToCart(myOrder);
                    JOptionPane.showMessageDialog(pane_cardtwo, "Seu pedido é o número " + posicao +" :D");
                    posicao++;
                } catch (Exception ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btn_pizzaActionPerformed

    private void btn_pastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pastActionPerformed
        String nomePedido = this.name_order_three.getText();
        String quantidade = this.input_qtd_three.getText();
        String observacoes = "";
        int table;
        if (quantidade.equalsIgnoreCase("") || quantidade.equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(pane_cardthree, "A quantidade não pode ser nula!");
        } else {
            table = Integer.parseInt(JOptionPane.showInputDialog(pane_cardthree, "Qual número da mesa?"));
            int option = JOptionPane.showConfirmDialog(pane_cardthree, "Possui alguma observação no pedido?");
            if (option == JOptionPane.YES_OPTION) {
                 observacoes = JOptionPane.showInputDialog(pane_cardthree, "Digite as observações abaixo!");
            } else if (option == JOptionPane.CANCEL_OPTION) {
                JOptionPane.showMessageDialog(pane_cardthree, "Cancelando pedido...");
                return;
            }

            Order myOrder = Order.newBuilder()
                    .setName(nomePedido)
                    .setCustomerTable(table)
                    .setObservations(observacoes)
                    .setQuantidade(Long.parseLong(quantidade))
                    .build();
            
            APIResponse response = userStub.registerOrder(myOrder);
            JOptionPane.showMessageDialog(pane_cardthree, response.getResponseMessage());
            
            if (response.getMessageCode() == 200) {
                try {
                    this.qtdCarrinho++;
                    this.cart_circle.setText(Integer.toString(this.qtdCarrinho));
                    this.carrinho.addOrderToCart(myOrder);
                    JOptionPane.showMessageDialog(pane_cardthree, "Seu pedido é o número " + posicao +" :D");
                    posicao++;
                } catch (Exception ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btn_pastActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFrame jFrame = new JFrame();
       jFrame.setContentPane(carrinho.getContentPane());
       jFrame.setLayout(new GridLayout(0,1));
       jFrame.setTitle("Meu carrinho");
       jFrame.setSize(new Dimension(300, 650));
       jFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        int option = JOptionPane.showConfirmDialog(pane_cardthree, "Deseja mesmo cancelar o seu pedido?");
        
        if (option == JOptionPane.YES_OPTION) {
            int pos = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o número da sua posição da fila fornecida:"));
            if (pos >= 1) {
                OrderID orderId = OrderID.newBuilder()
                        .setOrderNumber(pos-1)
                        .build();
                
                APIResponse response = userStub.cancelOrder(orderId);
                JOptionPane.showMessageDialog(null, response.getResponseMessage());
            
            if (response.getMessageCode() == 200) {
                try {
                    this.qtdCarrinho--;
                    this.cart_circle.setText(Integer.toString(this.qtdCarrinho));
                    this.carrinho.removeOrderToCart(pos-1);
                    JOptionPane.showMessageDialog(null, "Seu pedido da posição " + pos + " foi removido do carrinho!");
                } catch (Exception ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                
            } else {
                JOptionPane.showMessageDialog(null, "Posição inválida!");
            }
        }
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_hamb;
    private javax.swing.JButton btn_past;
    private javax.swing.JButton btn_pizza;
    private javax.swing.JLabel cart_circle;
    private javax.swing.JLabel cart_image;
    private javax.swing.JLabel cart_title;
    private javax.swing.JLabel descrip_order_one;
    private javax.swing.JLabel descrip_order_three;
    private javax.swing.JLabel descrip_order_two;
    private javax.swing.JLabel img_order_one;
    private javax.swing.JLabel img_order_three;
    private javax.swing.JLabel img_order_two;
    private javax.swing.JTextField input_qtd_one;
    private javax.swing.JTextField input_qtd_three;
    private javax.swing.JTextField input_qtd_two;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel name_order_one;
    private javax.swing.JLabel name_order_three;
    private javax.swing.JLabel name_order_two;
    private javax.swing.JPanel pane_cardone;
    private javax.swing.JPanel pane_cardthree;
    private javax.swing.JPanel pane_cardtwo;
    private javax.swing.JPanel pane_head;
    private javax.swing.JPanel panel_Cart;
    private javax.swing.JLabel qtd_order_one;
    private javax.swing.JLabel qtd_order_three;
    private javax.swing.JLabel qtd_order_two;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}


