package com.puccode.snacksclient.forms;

import java.awt.Color;
import javax.swing.JOptionPane;

public class Home extends javax.swing.JFrame {


    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        pane_cardone = new javax.swing.JPanel();
        name_order_one = new javax.swing.JLabel();
        img_order_one = new javax.swing.JLabel();
        descrip_order_one = new javax.swing.JLabel();
        input_qtd_one = new javax.swing.JTextField();
        qtd_order_one = new javax.swing.JLabel();
        btn_hamb = new javax.swing.JButton();
        pane_cardtwo = new javax.swing.JPanel();
        name_order_two = new javax.swing.JLabel();
        img_order_two = new javax.swing.JLabel();
        descrip_order_two = new javax.swing.JLabel();
        qtd_order_two = new javax.swing.JLabel();
        input_qtd_two = new javax.swing.JTextField();
        btn_pizza = new javax.swing.JButton();
        pane_cardthree = new javax.swing.JPanel();
        name_order_three = new javax.swing.JLabel();
        img_order_three = new javax.swing.JLabel();
        descrip_order_three = new javax.swing.JLabel();
        qtd_order_three = new javax.swing.JLabel();
        input_qtd_three = new javax.swing.JTextField();
        btn_past = new javax.swing.JButton();
        pane_head = new javax.swing.JPanel();
        title = new javax.swing.JLabel();

        jButton3.setText("Comprar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        pane_cardone.setBackground(new java.awt.Color(153, 189, 169));
        pane_cardone.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        name_order_one.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        name_order_one.setText("Hambúrguer");

        img_order_one.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/hamburguer (1).png"))); // NOI18N

        descrip_order_one.setBackground(new java.awt.Color(204, 204, 204));
        descrip_order_one.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        descrip_order_one.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descrip_order_one.setText("<html>Hambúrguer completo, 2 carnes, alface,<br/>tomate, picles e molho especial.</html>");
        descrip_order_one.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        descrip_order_one.setOpaque(true);

        input_qtd_one.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_qtd_one.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        qtd_order_one.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qtd_order_one.setText("Qtd:");

        btn_hamb.setBackground(new java.awt.Color(0, 102, 102));
        btn_hamb.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btn_hamb.setForeground(new java.awt.Color(255, 255, 255));
        btn_hamb.setText("Fazer pedido");
        btn_hamb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hambActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pane_cardoneLayout = new javax.swing.GroupLayout(pane_cardone);
        pane_cardone.setLayout(pane_cardoneLayout);
        pane_cardoneLayout.setHorizontalGroup(
            pane_cardoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descrip_order_one, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addGroup(pane_cardoneLayout.createSequentialGroup()
                .addGroup(pane_cardoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_cardoneLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pane_cardoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name_order_one)
                            .addComponent(img_order_one, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pane_cardoneLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(qtd_order_one, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pane_cardoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_hamb)
                            .addComponent(input_qtd_one, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pane_cardoneLayout.setVerticalGroup(
            pane_cardoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_cardoneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(name_order_one)
                .addGap(38, 38, 38)
                .addComponent(img_order_one)
                .addGap(27, 27, 27)
                .addComponent(descrip_order_one, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pane_cardoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qtd_order_one)
                    .addComponent(input_qtd_one, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btn_hamb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane_cardtwo.setBackground(new java.awt.Color(153, 189, 169));

        name_order_two.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        name_order_two.setText("Pizza");

        img_order_two.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pizza.png"))); // NOI18N

        descrip_order_two.setBackground(new java.awt.Color(204, 204, 204));
        descrip_order_two.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        descrip_order_two.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descrip_order_two.setText("<html>Pizza de calabresa: molho de tomate,<br/>calabresa, cebola, e tempero da casa.</html>");
        descrip_order_two.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        descrip_order_two.setOpaque(true);

        qtd_order_two.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qtd_order_two.setText("Qtd:");

        input_qtd_two.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_qtd_two.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btn_pizza.setBackground(new java.awt.Color(0, 102, 102));
        btn_pizza.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btn_pizza.setForeground(new java.awt.Color(255, 255, 255));
        btn_pizza.setText("Fazer pedido");
        btn_pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pizzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pane_cardtwoLayout = new javax.swing.GroupLayout(pane_cardtwo);
        pane_cardtwo.setLayout(pane_cardtwoLayout);
        pane_cardtwoLayout.setHorizontalGroup(
            pane_cardtwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descrip_order_two)
            .addGroup(pane_cardtwoLayout.createSequentialGroup()
                .addGroup(pane_cardtwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_cardtwoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(pane_cardtwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_cardtwoLayout.createSequentialGroup()
                                .addComponent(img_order_two)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_cardtwoLayout.createSequentialGroup()
                                .addComponent(name_order_two)
                                .addGap(111, 111, 111))))
                    .addGroup(pane_cardtwoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(qtd_order_two, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pane_cardtwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_pizza)
                            .addComponent(input_qtd_two, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pane_cardtwoLayout.setVerticalGroup(
            pane_cardtwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_cardtwoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(name_order_two)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img_order_two, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(descrip_order_two, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pane_cardtwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_qtd_two, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtd_order_two))
                .addGap(31, 31, 31)
                .addComponent(btn_pizza)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pane_cardthree.setBackground(new java.awt.Color(153, 189, 169));

        name_order_three.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        name_order_three.setText("Pastel");

        img_order_three.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pastel.jpg"))); // NOI18N

        descrip_order_three.setBackground(new java.awt.Color(204, 204, 204));
        descrip_order_three.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        descrip_order_three.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descrip_order_three.setText("<html>Pastel de frango com catupiry, <br/>bem recheado e saboroso!</html>");
        descrip_order_three.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        descrip_order_three.setOpaque(true);

        qtd_order_three.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qtd_order_three.setText("Qtd:");

        btn_past.setBackground(new java.awt.Color(0, 102, 102));
        btn_past.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btn_past.setForeground(new java.awt.Color(255, 255, 255));
        btn_past.setText("Fazer pedido");
        btn_past.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pane_cardthreeLayout = new javax.swing.GroupLayout(pane_cardthree);
        pane_cardthree.setLayout(pane_cardthreeLayout);
        pane_cardthreeLayout.setHorizontalGroup(
            pane_cardthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_cardthreeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(name_order_three)
                .addGap(100, 100, 100))
            .addComponent(descrip_order_three)
            .addGroup(pane_cardthreeLayout.createSequentialGroup()
                .addGroup(pane_cardthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_cardthreeLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(img_order_three, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pane_cardthreeLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(qtd_order_three, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pane_cardthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_past)
                            .addComponent(input_qtd_three, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pane_cardthreeLayout.setVerticalGroup(
            pane_cardthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_cardthreeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(name_order_three)
                .addGap(18, 18, 18)
                .addComponent(img_order_three, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(descrip_order_three, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pane_cardthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtd_order_three)
                    .addComponent(input_qtd_three, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btn_past)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane_head.setBackground(new java.awt.Color(255, 0, 0));

        title.setBackground(Color.red);
        title.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Restaurante Java Snacks");

        javax.swing.GroupLayout pane_headLayout = new javax.swing.GroupLayout(pane_head);
        pane_head.setLayout(pane_headLayout);
        pane_headLayout.setHorizontalGroup(
            pane_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pane_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pane_headLayout.createSequentialGroup()
                    .addGap(431, 431, 431)
                    .addComponent(title)
                    .addContainerGap(432, Short.MAX_VALUE)))
        );
        pane_headLayout.setVerticalGroup(
            pane_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pane_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pane_headLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(title)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(pane_cardone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(pane_cardtwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(pane_cardthree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addComponent(pane_head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pane_head, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pane_cardone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pane_cardtwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pane_cardthree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hambActionPerformed
        // TODO add your handling code here:
        String quantidade = this.input_qtd_one.getText();
        String observacoes = "";
        if (quantidade.equalsIgnoreCase("") || quantidade.equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(pane_cardone, "A quantidade não pode ser nula!");
        } else {
            int option = JOptionPane.showConfirmDialog(pane_cardone, "Possui alguma observação no pedido?");
            if (option == JOptionPane.YES_OPTION) {
                 observacoes = JOptionPane.showInputDialog(pane_cardone, "Digite as observações abaixo!");
            } else if (option == JOptionPane.CANCEL_OPTION) {
                JOptionPane.showMessageDialog(pane_cardone, "Cancelando pedido...");
                return;
            }
        }
    }//GEN-LAST:event_btn_hambActionPerformed

    private void btn_pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pizzaActionPerformed
        // TODO add your handling code here:
        String quantidade = this.input_qtd_two.getText();
        String observacoes = "";
        if (quantidade.equalsIgnoreCase("") || quantidade.equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(pane_cardtwo, "A quantidade não pode ser nula!");
            return;
        } else {
            int option = JOptionPane.showConfirmDialog(pane_cardtwo, "Possui alguma observação no pedido?");
            if (option == JOptionPane.YES_OPTION) {
                 observacoes = JOptionPane.showInputDialog(pane_cardtwo, "Digite as observações abaixo!");
            } else if (option == JOptionPane.CANCEL_OPTION) {
                JOptionPane.showMessageDialog(pane_cardtwo, "Cancelando pedido...");
                return;
            }
        }
        
        System.out.println("qtd: " + quantidade + " obs: " + observacoes);
    }//GEN-LAST:event_btn_pizzaActionPerformed

    private void btn_pastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pastActionPerformed
        // TODO add your handling code here:
        String quantidade = this.input_qtd_three.getText();
        String observacoes = "";
        if (quantidade.equalsIgnoreCase("") || quantidade.equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(pane_cardthree, "A quantidade não pode ser nula!");
            return;
        } else {
            int option = JOptionPane.showConfirmDialog(pane_cardthree, "Possui alguma observação no pedido?");
            if (option == JOptionPane.YES_OPTION) {
                 observacoes = JOptionPane.showInputDialog(pane_cardthree, "Digite as observações abaixo!");
            } else if (option == JOptionPane.CANCEL_OPTION) {
                JOptionPane.showMessageDialog(pane_cardthree, "Cancelando pedido...");
                return;
            }
        }
        
        System.out.println("qtd: " + quantidade + " obs: " + observacoes);
    }//GEN-LAST:event_btn_pastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hamb;
    private javax.swing.JButton btn_past;
    private javax.swing.JButton btn_pizza;
    private javax.swing.JLabel descrip_order_one;
    private javax.swing.JLabel descrip_order_three;
    private javax.swing.JLabel descrip_order_two;
    private javax.swing.JLabel img_order_one;
    private javax.swing.JLabel img_order_three;
    private javax.swing.JLabel img_order_two;
    private javax.swing.JTextField input_qtd_one;
    private javax.swing.JTextField input_qtd_three;
    private javax.swing.JTextField input_qtd_two;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel name_order_one;
    private javax.swing.JLabel name_order_three;
    private javax.swing.JLabel name_order_two;
    private javax.swing.JPanel pane_cardone;
    private javax.swing.JPanel pane_cardthree;
    private javax.swing.JPanel pane_cardtwo;
    private javax.swing.JPanel pane_head;
    private javax.swing.JLabel qtd_order_one;
    private javax.swing.JLabel qtd_order_three;
    private javax.swing.JLabel qtd_order_two;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}


